const names = [
    "Arun",
    "Vijay",
    "Rajesh",
    "Kumar",
    "Ravi",
    "Suresh",
    "Mani",
    "Srinivas",
    "Balaji",
    "Ganesh",
    "Karthik",
    "Prakash",
    "Muthu",
    "Sathish",
    "Venkatesh",
    "Anand",
    "Murugan",
    "Harish",
    "Rajkumar",
    "Tharun",
    "Siva",
    "Krishnan",
    "Gokul",
    "Sundar",
    "Ramkumar",
    "Naveen",
    "Senthil",
    "Ramesh",
    "Jagan",
    "Surya",
    "Dinesh",
    "Karthikeyan",
    "Rajiv",
    "Selvam",
    "Sankar",
    "Aravind",
    "Ashok",
    "Saravanan",
    "Vignesh",
    "Kannan",
    "Madhavan",
    "Gopal",
    "Shankar",
    "Hari",
    "Suresh",
    "Sivakumar",
    "Ravi Kumar",
    "Vigneshwar",
    "Siddharth",
    "Vasanth"
  ]

  export const randomName = () => {
    return names[Math.floor(Math.random()*names.length)];
  }


  const comments = [
    "Hi! How’s it going?",
    "Enna da, today’s plan?",
    "Suresh here, நன்றி!",
    "Thanks for your help!",
    "What’s the latest update?",
    "Can you explain more?",
    "Great job, thanks!",
    "Please give details.",
    "Really helpful info!",
    "Help me understand.",
    "Need more info.",
    "Didn’t get it.",
    "Please simplify it.",
    "Current status என்ன?",
    "Any assistance available?",
    "Looking for solution.",
    "When is fix?",
    "This is inconvenient.",
    "Thanks for help.",
    "Review this matter.",
    "More questions, help?",
    "Still don’t get.",
    "Steps to follow?",
    "Clear explanation, thanks.",
    "Asked before, again.",
    "When will reply?",
    "Your help is crucial.",
    "Need clarification here.",
    "When’s the solution?",
    "Explain how it works.",
    "How soon reply?",
    "Immediate resolution needed.",
    "How can assist?",
    "Tested fourth time.",
    "Confused, need help.",
    "Check other details.",
    "When will it complete?",
    "Need anything else?",
    "Clarify this process.",
    "Sending another email.",
    "How can help?",
    "Very useful info.",
    "Please reply soon.",
    "Submitted, what next?",
    "More questions, reach out.",
    "Help with issue.",
    "Clarify again please.",
    "Fix this problem.",
    "Contact me soon.",
    "Resolve that issue.",
    "நன்றி, அது உதவியாய்.",
    "சரி, எப்போது முடியும்?",
    "தகவல் தேவை, தயவுசெய்து.",
    "உதவிக்கேற்கிறேன், நான்.",
    "இது மிகவும் நன்றாகும்.",
    "வாருங்கள், இணைக்கவும், தயவுசெய்து.",
    "இது புரியவில்லை, தயவுசெய்து.",
    "எப்போது பதிலளிக்கலாம்?",
    "மேலும் விளக்கம் தேவை.",
    "எது சரியான வழி?",
    "இந்த தகவல் பின்பற்றவும்.",
    "நீங்கள் எப்போது பதிலளிக்கிறீர்கள்?",
    "உதவிக்கு நன்றி, மீண்டும்.",
    "அதற்கான தீர்வு தேவை.",
    "உங்கள் பதிலை எதிர்பார்க்கிறேன்.",
    "உங்களுக்கு தேவை என்ன?",
    "மீண்டும் கூறுங்கள், தயவுசெய்து.",
    "மேலும் விவரங்களை வழங்கவும்.",
    "இந்த விஷயத்தை சரிசெய்வது.",
    "அறிக்கையைச் சரிசெய்யுங்கள், தயவுசெய்து.",
    "தகவல்களைச் சரிசெய்யுங்கள், தயவுசெய்து.",
    "மூன்றாவது முறையாகவும், மீண்டும் சரிபார்க்கவும்.",
    "நான் இப்போது என்ன செய்ய வேண்டும்?",
    "அதிக விளக்கமாக தரவும்.",
    "இந்த விவரங்களைப் பகிரவும்."
  ]

  export const randomComments = () => {
    return comments[Math.floor(Math.random()*comments.length)]
  }